---
- hosts: webserver
  become: true
  vars:
    nginx_listen_port: 8080
    LOGSERVER_IP: 192.168.10.11

  tasks:    
    - name: Установка временной зоны MSK
      timezone:
        name: Europe/Moscow

    - name: Устанавливаем epel-репозиторий
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: Устанавливаем необходимые и вспомогательные пакеты через yum
      become: true
      yum:
        name: "{{item}}"
        state: present
      loop:
        - mc
        - nano
        - net-tools
        - yum-utils
        - nginx

    - name: Создаем конфигурацию nginx используя шаблон jinja2
      template:
        src: nginx.j2
        dest: /etc/nginx/nginx.conf
        validate: /usr/sbin/nginx -t -c %s
      tags:
        - nginx-configuration
   
    - name: Check NGINX configs
      shell: "/usr/sbin/nginx -t"
      register: nginx_config_status 

    - name: NGINX test status
      debug:
        msg: "{{ nginx_config_status }}"

    - name: Start and enable nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Add audit rules for nginx config files
      blockinfile:
        path: /etc/audit/rules.d/audit.rules
        block: |
          ## Audit of nginx configuration files changes
          -w /etc/nginx/nginx.conf -p wa -k nginx_conf
          -w /etc/nginx/default.d/ -p wa -k nginx_conf
      notify:
        - restart auditd

    - name: Install audispd-plugins
      yum:
        name: audispd-plugins
        state: present

    - name: Copy audispd config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: 'audispd-remote.conf',dest: '/etc/audisp/audisp-remote.conf'}
        - {src: 'au-remote.conf',dest: '/etc/audisp/plugins.d/au-remote.conf'}
        - {src: 'auditd.conf',dest: '/etc/audit/auditd.conf'}
      notify:
        - restart auditd

    - name: Copy rsyslog config
      copy:
        src: rsyslog.conf
        dest: /etc/rsyslog.conf
      notify:
        - restart rsyslog

  handlers:
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded

    - name: restart auditd
      command: service auditd restart

    - name: restart rsyslog
      systemd:
        name: rsyslog
        state: restarted





