---
- hosts: webserver
  become: true
  vars:
    nginx_listen_port: 80
    LOGSERVER_IP: 192.168.10.11

  tasks:    
    - name: Set timezone
      timezone:
        name: Europe/Moscow

    - name: Install epel repo
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: Install packages via yum
      become: true   
      yum:
        name: "{{item}}"
        state: present
      loop:
        - mc
        - nano
        - net-tools
        - yum-utils
        - nginx
        - audispd-plugins

    - name: Create nginx config using jinja2 template
      template:
        src: nginx.j2
        dest: /etc/nginx/nginx.conf
        validate: /usr/sbin/nginx -t -c %s
      tags:
        - nginx-configuration
        
    - name: Create web-site folder 
      become: true
      file:
        path: /opt/www
        state: directory
        owner: root
        mode: 0777
        
    - name: Copy index.html to web-site folder
      copy:
        src: index.html
        dest: /opt/www/index.html
        owner: root
        group: root
        mode: '0777'
      notify: reload nginx
   
    - name: Check nginx config
      shell: "/usr/sbin/nginx -t"
      register: nginx_config_status 

    - name: Start nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Check nginx config
      debug:
        msg: "{{ nginx_config_status }}"

    - name: Add auditd rules for nginx
      blockinfile:
        path: /etc/audit/rules.d/audit.rules
        block: |
          ## Audit of nginx configuration files changes
          -w /etc/nginx/nginx.conf -p wa -k nginx_conf
          -w /etc/nginx/default.d/ -p wa -k nginx_conf
      notify:
        - restart auditd

    - name: Copy audispd config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: 'auditd.conf',dest: '/etc/audit/auditd.conf'}
        - {src: 'audispd-remote.j2',dest: '/etc/audisp/audisp-remote.conf'}
        - {src: 'au-remote.conf',dest: '/etc/audisp/plugins.d/au-remote.conf'}
      notify:
        - restart auditd

    - name: Copy rsyslog config
      copy:
        src: rsyslog.j2
        dest: /etc/rsyslog.conf
      notify:
        - restart rsyslog

  handlers:
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded

    - name: restart auditd
      command: service auditd restart

    - name: restart rsyslog
      systemd:
        name: rsyslog
        state: restarted





