all:
  hosts:
    webserver:
      ansible_host: WEBSERVER_IP
      ansible_ssh_private_key_file: ./.vagrant/machines/webserver/virtualbox/private_key
    logserver:
      ansible_host: LOGSERVER_IP
      ansible_ssh_private_key_file: ./.vagrant/machines/logserver/virtualbox/private_key
    elkserver:
      ansible_host: ELKSERVER_IP
      ansible_ssh_private_key_file: ./.vagrant/machines/elkserver/virtualbox/private_key
