---
- hosts: logserver
  become: true
  vars:
    ELKSERVER_IP: 192.168.10.12

  tasks:    
    - name: Set timezone
      timezone:
        name: Europe/Moscow

    - name: Install epel repo
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: Install packages via yum
      become: true
      yum:
        name: "{{item}}"
        state: present
      loop:
        - mc
        - nano
        - net-tools
        - yum-utils
        - audispd-plugins
        - java-1.8.0

    - name: Copy rsyslog config
      copy:
        src: rsyslog.conf
        dest: /etc/rsyslog.conf
      notify:
        - restart rsyslog

    - name: Copy auditd config
      copy:
        src: auditd.conf
        dest: /etc/audit/auditd.conf
      notify:
        - restart auditd

    - name: Install elasticsearch repo for filebeat installation
      copy:
        src: elasticsearch.repo
        dest: /etc/yum.repos.d/

    - name: Install filebeat
      yum:
        name: filebeat
        state: present

    - name: Start filebeat
      systemd:
        name: filebeat
        state: started
        enabled: yes

    - name: Copy filebeat custom config
      copy:
        src: filebeat.j2
        dest: /etc/filebeat/filebeat.yml
      notify:
        - restart filebeat

  handlers:
    - name: restart rsyslog
      systemd:
        name: rsyslog
        state: restarted

    - name: restart filebeat
      systemd:
        name: filebeat
        state: restarted

    - name: restart auditd
      command: service auditd restart




